config/routes.rb
ChallengeMe::Application.routes.draw do
  root :to => "home#index"
  
  devise_for :users, controllers: { registrations: "registrations"}

  resources :users do
    member do
      get :solutions
      get :challenges
    end
  end

  resources :challenges, :solutions
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :user

  has_attached_file :challenge_file,
      :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"

  validates :name, presence: true, uniqueness: true
  validates :desc, presence: true, if: "challenge_file.blank?"

  validates :challenge_file, attachment_presence: true, if: "desc.blank?"
  validates :challenge_file, attachment_presence: true, if: "challenge_file.present?"
  validates :challenge_file, attachment_presence: true, if: "challenge_file.present?"

  scope :with_state, ->(state) { where(:state => state) }

  state_machine :state, :initial => :created do
    event :activate do
      transition :created => :active
    end

    event :close do
      transition :active => :closed
    end
  end

  def user_solution user
    Solution.where(challenge_id: self.id, user_id: user.id).first.try(:decorate)
  end
end

app/models/solution.rb
class Solution < ActiveRecord::Base

  belongs_to :user
  belongs_to :challenge

  has_attached_file :solution_file,
      :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"

 validates :desc, presence: true, if: "solution_file.blank?"

 validates :challenge_id, :user_id, presence: true

 validates :solution_file, attachment_presence: true, if: "desc.blank?"
 validates :solution_file, attachment_presence: true, if: "solution_file.present?"
 validates :solution_file, attachment_presence: true, if: "solution_file.present?"

 after_save :profile_solution

 def profile_solution
   
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :date, :closed, :user_id, :desc, :challenge_file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  respond_to :js

  before_action :set_solution, only: [:show, :edit, :update, :destroy]

  # GET /solutions
  # GET /solutions.json
  def index
    @solutions = Solution.all
  end

  # GET /solutions/1
  # GET /solutions/1.json
  def show
    respond_with @solution
  end

  # GET /solutions/new
  def new
    @solution = Solution.new(challenge_id: params[:challenge_id], user_id: current_user.id)
    
    respond_with @solution
  end

  # GET /solutions/1/edit
  def edit
  end

  # POST /solutions
  # POST /solutions.json
  def create
    @solution = Solution.new(solution_params)

    respond_to do |format|
      if @solution.save
        format.json { render action: 'show', status: :created, location: @solution }
        format.js   {}#redirect_to @solution, notice: 'Solution was successfully created.' }
      else
        format.json { render json: @solution.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # PATCH/PUT /solutions/1
  # PATCH/PUT /solutions/1.json
  def update
    respond_to do |format|
      if @solution.update(solution_params)
        format.json { head :no_content }
        format.js   {}
      else
        format.json { render json: @solution.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @challenge_id = @solution.challenge_id
    @solution.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js   {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solution
      @solution = Solution.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solution_params
      params.require(:solution).permit(:solution_file, :desc, :time, :memory, :lines, :points, :challenge_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def solutions
    @solutions = Solution.where(:user_id => params[:id]).all
  end

  def challenges
    @challenges = Challenge.where(:user_id => params[:id]).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper

  def owner_of_challenge? challenge
    challenge.user_id == current_user.try(:id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/challenges/_add_solution.html.haml
.pull-right
  = link_to 'Add a solution', 'javascript:void(0);', id: "add_solution", data: { :url => new_solution_path, :"challenge-id" => challenge_id }, class: "btn btn-success"

app/views/challenges/_form.html.haml
= simple_form_for(@challenge, html: { class: 'form-horizontal well' }) do |f|
  = f.error_notification
  = f.input :user_id, as: "hidden", input_html: { value: current_user.id }

  .form-group= f.input :name, :required => true, label_html: { class: 'col-lg-2'}, input_html: { class: 'form-control' }
  .form-group= f.input :desc, label_html: { class: 'col-lg-2'}, input_html: { class: 'form-control', rows: 5 }
  .form-group= f.input :challenge_file, label: :File, label_html: { class: 'col-lg-2'}, input_html: { class: 'col-lg-9' }
  =# f.file_field :challenge_file

  .form-actions.col-lg-offset-9= f.button :submit

app/views/challenges/edit.html.haml
%h1 Editing challenge

= render 'form'

= link_to 'Show', @challenge, class: "btn btn-primary"

app/views/challenges/index.html.haml
%h1 Listing challenges

%table
  %tr
    %th Name
    %th Date
    %th Closed
    %th User
    %th Desc
    %th Challenge file
    %th
    %th
    %th

  - @challenges.each do |challenge|
    %tr
      %td= challenge.name
      %td= challenge.date
      %td= challenge.closed
      %td= challenge.user
      %td= challenge.desc
      %td= challenge.challenge_file
      %td= link_to 'Show', challenge
      %td= link_to 'Edit', edit_challenge_path(challenge)
      %td= link_to 'Destroy', challenge, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Challenge', new_challenge_path

app/views/challenges/new.html.haml
%h1 New challenge

= render 'form'

app/views/challenges/show.html.haml
.panel.panel-info.challenge-extra-info
  .panel-heading
    %h1= @challenge.name

  .panel-body
    .challenge-desc= @challenge.desc
    = @challenge.file

  .panel-footer
    %p.text-left
      %b Author:
      = @challenge.user.name
    %p.text-left
      %b Date:
      = "@challenge.date"
    %p.text-left
      %b State:
      %span{ class: @challenge.state }= @challenge.state

- if current_user
  = @challenge.solution_area

app/views/home/index.html.haml
%h3 Welcome
%h4 Challenge yourself and others!!!!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Challenge Me"
      %meta{:content => content_for?(:description) ? yield(:description) : "Challenge Me", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application", "data-turbolinks-track" => true
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    = render 'shared/navigation'
    .container
      #left-panel.container.col-md-3
        = render 'shared/left_panel'
      #main-panel.container.col-md-7
        %header
          = render 'shared/messages'
        #main{:role => "main"}
          = yield
        %footer
      / ! end of #container
      #right-panel.container.col-md-2
        = render 'shared/right_panel'
    =# javascript_include_tag "application", "data-turbolinks-track" => true

app/views/shared/_left_panel.html.haml
%dl.scrollable
  - Challenge.all.each do |challenge|
    %dt= link_to challenge.name, challenge_path(challenge.id)
    %dd
      %small= challenge.desc

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, id: "flash_#{name}", class: "alert #{ name == :notice ? "alert-success" : "alert-danger" }"

app/views/shared/_navigation.html.haml
.navbar-wrapper
  .container
    .navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = link_to "Challenge Me", root_path, :class => 'navbar-brand'
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to :new_challenge, new_challenge_path
            - if user_signed_in?
              %li= link_to :my_solutions, solutions_user_path(current_user)
              %li= link_to :my_challenges, challenges_user_path(current_user)
          %ul.nav.navbar-nav.navbar-right.devise
            - if user_signed_in?
              %li= link_to 'Edit account', edit_user_registration_path, :class => "btn btn-primary"
            - else
              %li= link_to 'Sign up', new_user_registration_path, :class => "btn btn-primary"
            - if user_signed_in?
              %li= link_to 'Logout', destroy_user_session_path, :method=>'delete', :class => "btn btn-danger"
            - else
              %li= link_to 'Login', new_user_session_path, :class => "btn btn-success"

app/views/shared/_right_panel.html.haml
.panel.panel-warning
  .panel-heading
    %h4.classification= "Classificação"
  .panel-body
    %ol
      %li= "Bruno"
      %li= "Montero"
      %li= "Cardozo"
      %li= "Martinez"
      %li= "Cisse"
      %li= "Lima"

app/views/solutions/_edit.html.haml
= render 'form'

app/views/solutions/_form.html.haml
= simple_form_for(@solution, html: { class: 'form-horizontal well' }, remote: true) do |f|
  = f.error_notification
  
  = f.input :user_id,      as: :hidden, input_html: { value: @solution.user_id }
  = f.input :challenge_id, as: :hidden, input_html: { value: @solution.challenge_id }

  .form-group= f.input :desc, :required => true, label_html: { class: 'col-lg-2'}, input_html: { class: 'form-control', rows: 10 }
  .form-group= f.input :solution_file, label: :File, label_html: { class: 'col-lg-2'}, input_html: { class: 'col-lg-9' }

  .form-actions.col-lg-offset-9= f.button :submit

app/views/solutions/_new.html.haml
= render 'form'

app/views/solutions/_show.html.haml
.panel.panel-success.solution-extra-info
  .panel-heading
    %h2= "Solution"

  .panel-body
    %p
      %b Desc:
      = solution.desc

    = solution.file

  - if solution.challenge.active?
    .panel-footer
      = link_to 'Edit', edit_solution_path(solution), class: "btn btn-primary", remote: true
      = link_to 'Remove', solution_path(id: solution.id), method: :delete, class: "btn btn-danger", remote: true

app/views/solutions/create.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'show', solution: @solution).html_safe %>');

app/views/solutions/destroy.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'challenges/add_solution', challenge_id: @challenge_id).html_safe %>');

app/views/solutions/edit.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'edit').html_safe %>');

app/views/solutions/index.html.haml
%h1 Listing solutions

%table
  %tr
    %th Solution file
    %th Desc
    %th
    %th
    %th

  - @solutions.each do |solution|
    %tr
      %td= solution.solution_file
      %td= solution.desc
      %td= link_to 'Show', solution
      %td= link_to 'Edit', edit_solution_path(solution)
      %td= link_to 'Destroy', solution, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Solution', new_solution_path

app/views/solutions/new.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'new').html_safe %>');

app/views/solutions/show.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'show', solution: @solution).html_safe %>');

app/views/solutions/update.js.erb
$('#challenge_solution').html('<%= escape_javascript(render 'show', solution: @solution).html_safe %>');

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}

app/views/users/solutions.html.haml
.panel.panel-default
  .panel-heading Solutions
  .list-group
    - @solutions.each do |solution|
      - state = solution.challenge.state
      .list-group-item
        = link_to solution.challenge.name, challenge_path(solution.challenge)
        %span{ class: "#{state} pull-right" }= state